# _config.yml
title: Conception des systèmes à base du microcontroleur STM32F
email: spaulkab@gmail.com
description: Site d'accompagnement du cours d'ingénierie - Ressources, supports de cours et projets sur les STM32F
baseurl: ""
url: "https://plkab.github.io"
timezone: Europe/Paris

# Collections personnalisées
collections:
  projets:
    output: true
    permalink: /projets/:path/
  enseignements:
    output: true
    permalink: /ressources/:path/
  cours1:
    output: true
    permalink: /cours1/:path/
  

# Paramètres du site
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Personnalisation
navigation:
  - title: Accueil
    url: /
  - title: Ressources
    url: /ressources
  - title: Projets
    url: /projets
  - title: Cours 1
    url: /cours1
  
professeurs:
  - nom: "Ir. Paul S. Kabidu"
    role: "Enseignent en genie electrique"
    email: "spaulkab@gmail.com"